root <- '/Users/alessandrovadala/DOCUDESK/R-ebirth'; setwd(root)
library(relm)
stopifnot(normalizePath(find.package('relm')) == '/private/tmp/relm-f6d/library/relm')
e <- new.env(parent = asNamespace('relm'))
for (f in c('helper-directions.R', 'helper-direction-goldens.R')) sys.source(file.path('rebirth/tests/testthat',f), e)
files <- c('test-directions-boundaries.R','test-directions-goldens.R','test-directions-memory.R','test-package.R')
results <- lapply(files, function(f) testthat::test_file(file.path('rebirth/tests/testthat',f),env=e,reporter='summary'))
rows <- do.call(rbind,lapply(results,as.data.frame)); out <- Sys.getenv('RELM_F6D_EVIDENCE')
saveRDS(results,file.path(out,'tests.rds'))
write.csv(rows[,setdiff(names(rows),'result')],file.path(out,'tests.csv'),row.names=FALSE)
expected <- sum(vapply(files,function(f) sum(grepl('^test_that\\(',readLines(file.path('rebirth/tests/testthat',f)))), integer(1)))
stopifnot(nrow(rows)==expected, all(rows$failed==0L),!any(rows$error),!any(rows$skipped),all(rows$warning==0L),all(rows$passed>0L))
cat(sprintf('F6D_INSTALLED_BOUNDARIES_PASSED %d cases / %d expectations\n',nrow(rows),sum(rows$passed)))
notes <- capture.output(codetools::checkUsagePackage('relm'));writeLines(notes,file.path(out,'code-usage.txt'));stopifnot(length(notes)==0L)
