root <- '/Users/alessandrovadala/DOCUDESK/R-ebirth'; setwd(root)
library(relm)
stopifnot(normalizePath(find.package('relm')) == '/private/tmp/relm-f6c/library/relm')
e <- new.env(parent=asNamespace('relm'))
sys.source('rebirth/tests/testthat/helper-graphics.R', e)
r <- lapply(c('test-package.R','test-graphics-memory.R'), function(f)
  testthat::test_file(file.path('rebirth/tests/testthat',f),env=e,reporter='summary'))
rows <- do.call(rbind,lapply(r,as.data.frame));out <- Sys.getenv('RELM_F6C_EVIDENCE')
saveRDS(r,file.path(out,'focused-tests.rds'))
write.csv(rows[,setdiff(names(rows),'result')],file.path(out,'focused-tests.csv'),row.names=FALSE)
stopifnot(nrow(rows)==7L, sum(rows$passed)==27L, all(rows$failed==0L),
  !any(rows$error), !any(rows$skipped), all(rows$warning==0L))
cat('F6C_CI_PACKAGE_TESTS_PASSED 7 cases / 27 expectations\n')
notes <- capture.output(codetools::checkUsagePackage('relm'))
writeLines(notes,file.path(out,'code-usage.txt'))
stopifnot(length(notes)==0L)
cat('F6C_NAMESPACE_CODE_USAGE_PASSED\n')
