args <- commandArgs(trailingOnly = TRUE)
stopifnot(length(args) == 1L)
path <- normalizePath(args[[1L]], mustWork = TRUE)
stopifnot(!"relm" %in% names(getLoadedDLLs()))
dll <- dyn.load(path, local = TRUE, now = TRUE)
stopifnot(identical(normalizePath(dll[["path"]], mustWork = TRUE), path))
symbol <- getNativeSymbolInfo("wrap__rebirth_selftest_projection_ledger", PACKAGE = dll)
stopifnot(identical(symbol$numParameters, 0L))
stopifnot(identical(normalizePath(symbol$dll[["path"]], mustWork = TRUE), path))
result <- .Call(symbol)
stopifnot(identical(result, list(ok = TRUE)))
invisible(gc())
cat("F6E_PROJECTION_R_HOSTED_SUCCESS cases=47 rejections=19 models=0\n")
