# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib rebirth, .registration = TRUE
NULL

rebirth_model_load <- function(path, context_length, gpu_layers, backend, mmap) .Call(wrap__rebirth_model_load, path, context_length, gpu_layers, backend, mmap)

rebirth_handle_close <- function(ptr) .Call(wrap__rebirth_handle_close, ptr)

rebirth_handle_is_closed <- function(ptr) .Call(wrap__rebirth_handle_is_closed, ptr)

rebirth_available_backends <- function() .Call(wrap__rebirth_available_backends)

rebirth_tokenize <- function(ptr, text, add_special, parse_special) .Call(wrap__rebirth_tokenize, ptr, text, add_special, parse_special)

rebirth_detokenize <- function(ptr, ids) .Call(wrap__rebirth_detokenize, ptr, ids)

rebirth_generate <- function(ptr, prompt, chat, max_tokens, temperature, top_p, seed, stop) .Call(wrap__rebirth_generate, ptr, prompt, chat, max_tokens, temperature, top_p, seed, stop)

rebirth_embed <- function(ptr, texts, pooling, normalize) .Call(wrap__rebirth_embed, ptr, texts, pooling, normalize)

rebirth_trace <- function(ptr, prompts, layers, positions_mode, positions_values, components) .Call(wrap__rebirth_trace, ptr, prompts, layers, positions_mode, positions_values, components)

rebirth_selftest_new_handle <- function() .Call(wrap__rebirth_selftest_new_handle)

rebirth_selftest_panic <- function() .Call(wrap__rebirth_selftest_panic)

# nolint end
