# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib rebirth, .registration = TRUE
NULL

rebirth_model_load <- function(path, context_length, gpu_layers, backend, mmap) .Call(wrap__rebirth_model_load, path, context_length, gpu_layers, backend, mmap)

rebirth_handle_close <- function(ptr) .Call(wrap__rebirth_handle_close, ptr)

rebirth_handle_is_closed <- function(ptr) .Call(wrap__rebirth_handle_is_closed, ptr)

rebirth_available_backends <- function() .Call(wrap__rebirth_available_backends)

rebirth_tokenize <- function(ptr, text, add_special, parse_special) .Call(wrap__rebirth_tokenize, ptr, text, add_special, parse_special)

rebirth_detokenize <- function(ptr, ids) .Call(wrap__rebirth_detokenize, ptr, ids)

rebirth_generate <- function(ptr, prompt, chat, max_tokens, temperature, top_p, seed, stop) .Call(wrap__rebirth_generate, ptr, prompt, chat, max_tokens, temperature, top_p, seed, stop)

rebirth_logits <- function(ptr, prompt, top) .Call(wrap__rebirth_logits, ptr, prompt, top)

rebirth_embed <- function(ptr, texts, pooling, normalize) .Call(wrap__rebirth_embed, ptr, texts, pooling, normalize)

rebirth_trace <- function(ptr, prompts, layers, positions_mode, positions_values, components, spill, budget_bytes, spill_path, model_id, trace_id, spec_key) .Call(wrap__rebirth_trace, ptr, prompts, layers, positions_mode, positions_values, components, spill, budget_bytes, spill_path, model_id, trace_id, spec_key)

rebirth_intervene <- function(ptr, n_embd, n_layer, steer_layers, steer_vectors, ablate_layers, ablate_neurons, ablate_values) .Call(wrap__rebirth_intervene, ptr, n_embd, n_layer, steer_layers, steer_vectors, ablate_layers, ablate_neurons, ablate_values)

rebirth_selftest_new_handle <- function() .Call(wrap__rebirth_selftest_new_handle)

rebirth_selftest_panic <- function() .Call(wrap__rebirth_selftest_panic)

rebirth_selftest_trace_tokens_spill <- function(ptr, tokens, spill, budget_bytes, spill_path, model_id, trace_id, spec_key) .Call(wrap__rebirth_selftest_trace_tokens_spill, ptr, tokens, spill, budget_bytes, spill_path, model_id, trace_id, spec_key)

# nolint end
