args<-commandArgs(TRUE);stopifnot(length(args)==2L)
dll<-dyn.load(normalizePath(args[1],mustWork=TRUE),local=TRUE,now=TRUE)
symbol<-getNativeSymbolInfo('wrap__make_relm_wrappers',PACKAGE=dll)
stopifnot(identical(symbol$numParameters,2L))
wrappers<-.Call(symbol,TRUE,'relm');stopifnot(is.character(wrappers),length(wrappers)==1L)
header<-paste0('# Generated by extendr: Do not edit by hand\n# nolint start\n\n',
 "#' @usage NULL\n#' @useDynLib relm, .registration = TRUE\nNULL\n\n")
writeChar(paste0(header,wrappers,'# nolint end\n'),args[2],eos=NULL,useBytes=TRUE)
invisible(parse(args[2]));cat('F6E_WRAPPERS generated_from_current_default_DLL=TRUE\n')
