library(relm)
root<-'/Users/alessandrovadala/DOCUDESK/R-ebirth';setwd(root)
stopifnot(normalizePath(find.package('relm'))=='/private/tmp/relm-f6d/library/relm')
out<-Sys.getenv('RELM_F6D_EVIDENCE');e<-new.env(parent=asNamespace('relm'))
r<-testthat::test_file('rebirth/tests/testthat/test-directions-model.R',env=e,reporter='summary')
saveRDS(r,file.path(out,'tests.rds'));rows<-as.data.frame(r)
write.csv(rows[,setdiff(names(rows),'result')],file.path(out,'tests.csv'),row.names=FALSE)
stopifnot(nrow(rows)==1L,rows$passed==4L,rows$failed==0L,!rows$error,!rows$skipped,rows$warning==0L)
cat('F6D_ACTUAL_MODEL_RESET_PASSED 1 case / 4 expectations / 5 eight-token calls\n')
