# WP6a: the in-repo synthetic 2-layer llama GGUF loads on this build and
# summary() reports its tiny dimensions. This is the WP1 <-> WP6a integration
# check and the proof that the committed synthetic model is a genuinely valid
# GGUF (llama.cpp b9726 parses it), not just bytes on disk.
#
# The fixture is a byte-identical copy of the canonical
# tests/llm-golden/synthetic/synthetic-llama-2l.gguf, regenerated by
# tests/llm-golden/synthetic/build_synthetic.py; the golden self-check enforces
# the two stay identical. Values below are fixed by synthetic_model.CONFIG.

synthetic_model_path <- function() {
  p <- testthat::test_path("fixtures", "synthetic-llama-2l.gguf")
  skip_if_not(file.exists(p), "synthetic GGUF fixture is missing")
  p
}

test_that("the synthetic GGUF loads and reports its tiny dimensions", {
  m <- llm(synthetic_model_path())
  on.exit(close(m), add = TRUE)

  expect_s3_class(m, "llm")
  expect_identical(m$architecture, "llama")
  expect_identical(m$layers, 2L)
  expect_identical(m$hidden_size, 32L)
  expect_identical(m$quantization, "F32")
  expect_identical(m[[".vocab_size"]], 48L)
  expect_identical(m[[".context_train"]], 4096L)
  # 23,712 F32 parameters (token_embd + output + norms + 2 blocks); see
  # synthetic_model.build_weights().
  expect_identical(m$parameters, 23712)
  expect_true(m$backend %in% c("metal", "cuda", "cpu"))
})

test_that("the synthetic model loads on the CPU backend", {
  # CI has no GPU; loading it explicitly on CPU guarantees the download-free
  # exact-value path runs on every CI platform.
  m <- llm(synthetic_model_path(), backend = "cpu")
  on.exit(close(m), add = TRUE)
  expect_identical(m$backend, "cpu")
  expect_identical(m$layers, 2L)
  expect_identical(m$hidden_size, 32L)
})

test_that("summary() on the synthetic model carries the tiny vocabulary", {
  m <- llm(synthetic_model_path())
  on.exit(close(m), add = TRUE)
  s <- summary(m)
  expect_s3_class(s, "summary.llm")
  expect_identical(s$vocab_size, 48L)
  expect_identical(s$layers, 2L)
  expect_identical(s$quantization, "F32")
})
