# WP6b: cross-validate llm_trace()'s activation taps against an INDEPENDENT
# PyTorch/transformers fp32 reference on a REAL model (Qwen2.5-0.5B-Instruct).
#
# The reference (goldens under tests/llm-golden/qwen/, generated by the pinned
# reference_forward_hf.py) captures the SAME quantities llm_trace taps -- residual
# (l_out, the decoder-block output) and mlp_out (ffn_out, the MLP sub-layer output)
# -- from forward hooks on the fp32 HF model. Its blob is duplicated into
# fixtures/qwen-hf-activations.f32 so this test reaches it under R CMD check.
#
# NOTE on attn_out (D-014): the reference also captures self_attn.o_proj but does
# NOT commit/compare it, because llm_trace does not observe attn_out on qwen2 (it
# names only the pre-projection kqv_out) and raises relm_error_trace. That honest
# error is asserted by an existing [MODEL] test in test-llm-trace.R; it is not
# duplicated here.
#
# What runs where (rule 8e):
#   * "golden fixture is well-formed" needs no model -> per-commit CI (R CMD check).
#   * The numerical comparison is [MODEL]-gated on RELM_TEST_MODEL_QWEN (a local
#     Qwen2.5-0.5B GGUF, e.g. the Q8_0 CI pin). It runs on the founder's Mac /
#     nightly and NEVER downloads a model.
#
# Tolerance. Scale-robust metrics (per-layer Spearman, per-row cosine, and an
# atol+rtol max|delta| bound) are used because Qwen carries "massive activations" (some
# residual dims are O(10^3)), so an absolute-only tolerance is meaningless. Diagnosed
# 2026-07-07 on Qwen2.5-0.5B, all 24 layers x {residual, mlp_out}, last token:
#   * The engine agrees with the HF fp32 reference to cosine ~0.999 at LAYER 1 and
#     DIVERGES with depth to min per-layer Spearman ~0.973 / min per-row cosine ~0.964
#     by layer 24. This gap is INTRINSIC llama.cpp-vs-HF divergence, NOT Q8_0: it is
#     backend-independent (CPU == Metal) and quantization-independent (fp16 == Q8_0),
#     and it is functionally BENIGN -- llm_logits and HF agree on the same top-5 next
#     tokens (only near-tied #1/#2 reorder). Early-layer 0.999 + logit agreement prove
#     the taps capture the RIGHT quantity; the rest is compounding float divergence
#     between two independent implementations of a numerically sensitive 0.5B model.
#   * Extrema across backends/quants: min Spearman 0.973, min cosine 0.964, max
#     per-(layer,comp) |delta| 2.72, max relative |delta| 0.27 (a tiny-magnitude mlp layer).
# The gates sit a clear margin below those and FAR above a real defect (a wrong tensor
# / off-by-one layer / BOS shift collapses cosine & Spearman toward 0; an off-by-one
# also blows the per-(layer,comp) |delta| bound where the residual scale jumps between
# adjacent layers). HONESTY: this does NOT reach CLAUDE.md's "rank-correlation >=
# 0.999/layer on real models" -- that is unachievable against an INDEPENDENT (HF)
# implementation on 0.5B; 0.999 would need the same-implementation unpatched-llama.cpp
# leg, or a larger/less-sensitive model. Flagged for doc reconciliation (WP6b handoff).

# --- twin-pins to tests/llm-golden/qwen/goldens/manifest.json ----------------
# Regenerating the golden updates GOLDEN_SHA256 + these dims (golden-update skill).
GOLDEN_SHA256 <- "dcc355a35f2e3083b57fa4899587e65939707903ed3c853b01e20861ece22f32"
GOLDEN_N_LAYERS <- 24L
GOLDEN_N_COMPONENTS <- 2L
GOLDEN_N_PROMPTS <- 3L
GOLDEN_N_EMBD <- 896L
GOLDEN_COMPONENTS <- c("residual", "mlp_out") # component axis order in the blob
GOLDEN_PROMPTS <- c(
  "The cat sat on the mat.",
  "Paris is the capital of France.",
  "Water boils at one hundred degrees Celsius."
)
# HF 0-based token ids per prompt (llm_tokens' 1-based ids minus 1 must equal these).
GOLDEN_TOKEN_IDS_0BASED <- list(
  c(785L, 8251L, 7578L, 389L, 279L, 5517L, 13L),
  c(59604L, 374L, 279L, 6722L, 315L, 9625L, 13L),
  c(28253L, 88955L, 518L, 825L, 7739L, 12348L, 61347L, 13L)
)

# --- justified cross-implementation tolerances (see the header) --------------
MIN_LAYER_SPEARMAN <- 0.94 # observed min 0.973 (cross-backend); a defect gives << 0.9
MIN_ROW_COSINE <- 0.94 # observed min 0.964 (cross-backend); a defect gives << 0.9
DELTA_ATOL <- 1.0 # per-(layer,comp) max|delta| <= ATOL + RTOL * max|golden_slice|
DELTA_RTOL <- 0.06 # observed maxima leave ~1.7-2x headroom under this bound
GLOBAL_MAXABS_BLOWUP <- 8.0 # coarse blow-up guard (observed global max|delta| 2.72)

# --- the shared scale-robust agreement gate (rule 8f: thresholds live ONLY above) -
# Given an engine slice `eng` and the golden slice `gol` it must reproduce (both
# [n_prompts x n_embd]), compute the four scale-robust metrics and a single pass/fail
# against the pinned thresholds:
#   (1) per-layer Spearman  >= MIN_LAYER_SPEARMAN   (rank agreement, scale-free)
#   (2) per-row   cosine    >= MIN_ROW_COSINE       (direction agreement, per prompt)
#   (3) max|delta| <= DELTA_ATOL + DELTA_RTOL*scale (absolute agreement, scale-aware)
#   (4) max|delta| <  GLOBAL_MAXABS_BLOWUP          (coarse blow-up guard)
# BOTH callers -- the [MODEL] cross-validation (real engine vs golden) and the
# model-free mutation test (deliberately mutated golden vs golden) -- go through here,
# so no threshold is duplicated or can drift between them. (1)+(2) catch a wrong /
# shifted tensor; (3)+(4) catch a pure scale defect that (1)+(2) are invariant to.
trace_golden_gate <- function(eng, gol) {
  stopifnot(identical(dim(eng), dim(gol)))
  mad <- max(abs(eng - gol))
  gscale <- max(abs(gol))
  spear <- suppressWarnings(cor(as.vector(eng), as.vector(gol), method = "spearman"))
  cosr <- vapply(seq_len(nrow(eng)), function(r) {
    sum(eng[r, ] * gol[r, ]) / (sqrt(sum(eng[r, ]^2)) * sqrt(sum(gol[r, ]^2)))
  }, numeric(1))
  mincos <- min(cosr)
  bound <- DELTA_ATOL + DELTA_RTOL * gscale
  list(
    spearman = spear, min_cosine = mincos, max_abs_delta = mad,
    rel_max = mad / gscale, bound = bound,
    pass = spear >= MIN_LAYER_SPEARMAN && mincos >= MIN_ROW_COSINE &&
      mad <= bound && mad < GLOBAL_MAXABS_BLOWUP
  )
}

qwen_model_path <- function() {
  p <- path.expand(Sys.getenv("RELM_TEST_MODEL_QWEN"))
  skip_if_not(
    nzchar(p) && file.exists(p),
    "RELM_TEST_MODEL_QWEN is not set to an existing GGUF file"
  )
  p
}

golden_fixture_path <- function() {
  p <- testthat::test_path("fixtures", "qwen-hf-activations.f32")
  skip_if_not(file.exists(p), "qwen-hf-activations.f32 golden fixture is missing")
  p
}

# The committed golden as a flat numeric vector (float32 on disk -> R double).
read_golden <- function(path) {
  n <- GOLDEN_N_LAYERS * GOLDEN_N_COMPONENTS * GOLDEN_N_PROMPTS * GOLDEN_N_EMBD
  v <- readBin(path, what = "double", n = n, size = 4L, endian = "little")
  stopifnot(length(v) == n)
  v
}

# One (layer, component) slice as a [n_prompts x n_embd] matrix, rows in
# (prompt, last-position) order -- matching as.matrix.relm_trace's row order.
# li0/ci0 are 0-based; the blob is C-order [layer, component, prompt, neuron].
golden_slice <- function(v, li0, ci0) {
  block <- GOLDEN_N_PROMPTS * GOLDEN_N_EMBD
  start <- (li0 * GOLDEN_N_COMPONENTS + ci0) * block
  matrix(v[(start + 1L):(start + block)],
    nrow = GOLDEN_N_PROMPTS, ncol = GOLDEN_N_EMBD, byrow = TRUE
  )
}

# --- fixture integrity (no model; runs in per-commit CI) ---------------------

test_that("the committed HF activation golden fixture is well-formed and matches its SHA256", {
  # Defect caught: a corrupted / truncated / mis-committed / hand-edited golden
  # (golden discipline). The SHA256 pin makes any byte change fail here, BEFORE the
  # [MODEL] test would silently compare against a wrong reference. Mirrors the
  # valence-direction integrity test.
  path <- golden_fixture_path()
  expected_bytes <- GOLDEN_N_LAYERS * GOLDEN_N_COMPONENTS * GOLDEN_N_PROMPTS * GOLDEN_N_EMBD * 4
  expect_identical(file.size(path), expected_bytes)
  expect_identical(unname(tools::sha256sum(path)), GOLDEN_SHA256)

  v <- read_golden(path)
  expect_true(all(is.finite(v)))
  expect_false(all(v == 0)) # not a zeroed/blank blob
  # A slice is the promised shape and non-degenerate (distinct layers differ).
  s1 <- golden_slice(v, 0L, 0L)
  s2 <- golden_slice(v, 11L, 0L)
  expect_identical(dim(s1), c(GOLDEN_N_PROMPTS, GOLDEN_N_EMBD))
  expect_false(isTRUE(all.equal(s1, s2)))
})

# --- model-free mutation test: the gate has teeth (no model; per-commit CI) --
# This is the WP6b mutation-test acceptance. It runs in per-commit CI (R CMD check):
# it reads ONLY the committed golden blob, sets no RELM_TEST_MODEL_QWEN and loads
# no model (rule 8e). It locks in the non-gameability the [MODEL] test can only show
# with a real model (D-018): feed a DELIBERATELY MUTATED slice through the SAME
# trace_golden_gate() the [MODEL] test uses and prove the gate REJECTS it -- satisfying
# ARCHITECTURE.md:52 ("harness B's off-by-one mutation test (inject layer+1) must fail
# loudly") without a model. The [MODEL] test proved a real +1 shift breaches every gate
# (D-018: min Spearman -0.26, blow-up 55.6); this proves the same gate has teeth per-commit.

# Apply `mutate(v, li0, ci0)` to build the (mutated) engine slice the gate sees for each
# (layer, component), compare it to the TRUE golden slice, and return TRUE iff EVERY
# slice passes -- the collection-level verdict the [MODEL] test enforces (its
# `violations` vector must be empty). A mutation is "caught" iff this returns FALSE.
gate_all_slices_pass <- function(v, mutate, layers0 = 0:(GOLDEN_N_LAYERS - 1L)) {
  for (li0 in layers0) {
    for (ci0 in 0:(GOLDEN_N_COMPONENTS - 1L)) {
      if (!trace_golden_gate(mutate(v, li0, ci0), golden_slice(v, li0, ci0))$pass) {
        return(FALSE)
      }
    }
  }
  TRUE
}

test_that("golden gate is SATISFIED when a slice is compared to itself (no-op guard)", {
  # Defect caught: a vacuous / always-failing gate. If a golden slice cannot clear its
  # OWN thresholds, every pass/fail verdict below is meaningless. This control is what
  # gives the three mutation rejections their force. Runs per-commit (no model).
  v <- read_golden(golden_fixture_path())
  expect_true(gate_all_slices_pass(v, function(v, li0, ci0) golden_slice(v, li0, ci0)))

  g <- trace_golden_gate(golden_slice(v, 11L, 0L), golden_slice(v, 11L, 0L))
  expect_true(g$pass)
  expect_equal(g$spearman, 1)
  expect_equal(g$min_cosine, 1)
  expect_equal(g$max_abs_delta, 0)
})

test_that("golden gate CATCHES a +1 layer-shift mutation (off-by-one, ARCHITECTURE section 4)", {
  # Defect caught: an off-by-one in engine<->API layer indexing (the canonical defect
  # class, ARCHITECTURE section 4 / ARCHITECTURE.md:52) -- the engine returns layer
  # L+1's activation when asked for layer L. Runs per-commit (no model).
  v <- read_golden(golden_fixture_path())
  # Aggregate, mirroring the [MODEL] all-layers verdict: ask for L, get L+1 (the top
  # layer has no L+1, so shift over layers 0..N-2). Not one slice survives.
  expect_false(gate_all_slices_pass(
    v, function(v, li0, ci0) golden_slice(v, li0 + 1L, ci0),
    layers0 = 0:(GOLDEN_N_LAYERS - 2L)
  ))
  # Focused: adjacent mlp_out layers differ in BOTH rank and direction, so the shift
  # collapses Spearman and cosine far below their floors -- not a marginal miss.
  g <- trace_golden_gate(golden_slice(v, 2L, 1L), golden_slice(v, 1L, 1L))
  expect_false(g$pass)
  expect_lt(g$min_cosine, MIN_ROW_COSINE)
  expect_lt(g$spearman, MIN_LAYER_SPEARMAN)
})

test_that("golden gate CATCHES a wrong-component swap (residual<->mlp_out)", {
  # Defect caught: the tap reads the WRONG named tensor -- mlp_out where residual was
  # requested, or vice versa (a tensor-name mismatch in trace.rs). The mutated engine
  # slice is the sibling component at the same layer. Runs per-commit (no model).
  v <- read_golden(golden_fixture_path())
  expect_false(gate_all_slices_pass(
    v, function(v, li0, ci0) golden_slice(v, li0, 1L - ci0)
  ))
  # Focused (0-based layer 2): residual and mlp_out are distinct quantities, so the swap
  # collapses direction agreement. (At layer 0 residual ~= mlp_out and the swap slips
  # through THERE -- caught by the OTHER layers, exactly how the all-layers gate works.)
  g <- trace_golden_gate(golden_slice(v, 2L, 1L), golden_slice(v, 2L, 0L))
  expect_false(g$pass)
  expect_lt(g$min_cosine, MIN_ROW_COSINE)
})

test_that("golden gate CATCHES a scalar blow-up that cosine/Spearman are BLIND to", {
  # Defect caught: a pure SCALE error -- a missing/extra normalization or a wrong scale
  # factor in a kernel, so the tap reads activations k-times too large. Cosine (per-row,
  # scale-free) and Spearman (rank, monotone-invariant) CANNOT see a positive rescale:
  # both stay exactly 1.0. Only the absolute atol+rtol bound and the 8.0 blow-up guard
  # reject it -- proving those two checks are load-bearing, not decorative. No model.
  v <- read_golden(golden_fixture_path())
  expect_false(gate_all_slices_pass(v, function(v, li0, ci0) 3 * golden_slice(v, li0, ci0)))

  # Focused on a large-scale residual slice: rank + direction are PERFECTLY preserved,
  # yet max|delta| (2x the scale) smashes both the bound and the 8.0 blow-up guard.
  gol <- golden_slice(v, 23L, 0L)
  g <- trace_golden_gate(3 * gol, gol)
  expect_equal(g$spearman, 1) # rank-blind
  expect_equal(g$min_cosine, 1) # direction-blind
  expect_gt(g$max_abs_delta, GLOBAL_MAXABS_BLOWUP) # caught ONLY by the absolute guards
  expect_false(g$pass)
})

# --- [MODEL] numerical cross-validation --------------------------------------

test_that("llm_trace() on Qwen2.5-0.5B matches the HF fp32 activation golden (Q8_0 tolerance) [MODEL]", {
  model_path <- qwen_model_path()
  v <- read_golden(golden_fixture_path())

  m <- llm(model_path)
  on.exit(close(m), add = TRUE)
  skip_if_not(
    identical(m$architecture, "qwen2") && m$hidden_size == GOLDEN_N_EMBD &&
      m$layers == GOLDEN_N_LAYERS,
    "RELM_TEST_MODEL_QWEN is not the Qwen2.5-0.5B the golden was built from"
  )

  # ---- alignment guard (audit L-7): llm_trace must tokenize exactly as the HF
  # reference did, or aligned-position comparison is meaningless. A future BOS /
  # tokenizer divergence fails HERE with a clear message, not as a mystery delta.
  for (i in seq_along(GOLDEN_PROMPTS)) {
    ids0 <- as.integer(llm_tokens(m, GOLDEN_PROMPTS[i])) - 1L
    expect_identical(
      ids0, GOLDEN_TOKEN_IDS_0BASED[[i]],
      info = sprintf("prompt %d tokenization must match the HF reference (BOS alignment)", i)
    )
  }

  tr <- llm_trace(
    m, GOLDEN_PROMPTS,
    layers = seq_len(GOLDEN_N_LAYERS), positions = "last",
    components = GOLDEN_COMPONENTS, spill = FALSE
  )
  expect_s3_class(tr, "relm_trace")
  expect_setequal(unique(tr$component), GOLDEN_COMPONENTS)

  # ---- alignment guard: the single captured token_pos per prompt is its LAST
  # (1-based) position == n_tokens. An extra leading token (BOS) would shift these.
  for (i in seq_along(GOLDEN_PROMPTS)) {
    tp <- unique(tr$token_pos[tr$prompt_id == i])
    expect_identical(tp, length(GOLDEN_TOKEN_IDS_0BASED[[i]]))
  }

  # ---- per-(layer, component) numerical agreement -------------------------
  worst_spear <- 1
  worst_cos <- 1
  worst_rel <- 0
  global_maxabs <- 0
  violations <- character(0)
  for (li in seq_len(GOLDEN_N_LAYERS)) {
    for (ci in seq_len(GOLDEN_N_COMPONENTS)) {
      eng <- as.matrix(tr, layer = li, component = GOLDEN_COMPONENTS[ci])
      gol <- golden_slice(v, li - 1L, ci - 1L)
      expect_identical(dim(eng), dim(gol))

      g <- trace_golden_gate(eng, gol) # the SAME gate the model-free mutation test drives
      worst_spear <- min(worst_spear, g$spearman)
      worst_cos <- min(worst_cos, g$min_cosine)
      worst_rel <- max(worst_rel, g$rel_max)
      global_maxabs <- max(global_maxabs, g$max_abs_delta)
      if (!g$pass) {
        violations <- c(violations, sprintf(
          "L%02d/%s: spearman=%.4f cos=%.4f max|delta|=%.3f (bound %.3f)",
          li, GOLDEN_COMPONENTS[ci], g$spearman, g$min_cosine, g$max_abs_delta, g$bound
        ))
      }
    }
  }

  # The empty-vector expectation names the exact failing (layer, component) rows.
  expect_identical(violations, character(0))
  expect_gte(worst_spear, MIN_LAYER_SPEARMAN)
  expect_gte(worst_cos, MIN_ROW_COSINE)
  expect_lt(global_maxabs, GLOBAL_MAXABS_BLOWUP)

  # Report the observed numbers in the nightly log (rule 8e).
  message(sprintf(
    "[MODEL] llm_trace vs HF fp32 golden (Q8_0): min layer spearman=%.4f, min row cosine=%.4f, max rel|delta|=%.4f, global max|delta|=%.3f",
    worst_spear, worst_cos, worst_rel, global_maxabs
  ))
})
