args <- commandArgs(trailingOnly=TRUE)
stopifnot(length(args)==2L)
path <- normalizePath(args[[1L]],mustWork=TRUE)
model <- normalizePath(args[[2L]],mustWork=TRUE)
stopifnot(!"relm" %in% names(getLoadedDLLs()))
dll <- dyn.load(path,local=TRUE,now=TRUE)
symbol <- getNativeSymbolInfo("wrap__rebirth_selftest_projection_constructor",PACKAGE=dll)
stopifnot(identical(symbol$numParameters,1L))
stopifnot(identical(normalizePath(symbol$dll[["path"]],mustWork=TRUE),path))
result <- .Call(symbol,model)
stopifnot(identical(result,list(ok=TRUE)))
invisible(gc())
cat("F6E_CONSTRUCTOR_R_HOSTED_SUCCESS outcomes=1 cases=18 rejections=10 model_loads=1\n")
