list(class = c("relm_error_intervention", "relm_error", "error", 
"condition"), message = "Projection admission refused: invalid shape, capacity, ownership, arithmetic, or budget.", 
    fields = structure(list(message = "Projection admission refused: invalid shape, capacity, ownership, arithmetic, or budget.", 
        call = projection_prepare(m, entry, max_bytes, existing_direction_estimate, 
            direction_application = direction_application), reason = "Projection admission refused: invalid shape, capacity, ownership, arithmetic, or budget."), class = c("relm_error_intervention", 
    "relm_error", "error", "condition")), exact_budget = 1520395, 
    profile = list(version = 2, direction_arc_header_bytes = 16, 
        plan_arc_bytes = 48, site_bytes = 32, runtime_bytes = 5072, 
        probe_state_bytes = 56, model_owner_bytes = 912, derive_frame_bytes = 11959, 
        callback_frame_bytes = 429, probe_frame_bytes = 153, 
        residual_probe_fixed_bytes = 522, ffi_fixed_bytes = 1768, 
        adapter_fixed_bytes = 256, error_format_bytes = 150, 
        metadata_owner_bytes = 0, slot_bytes = 64, proof_bytes = 152, 
        projection_info_bytes = 128, cpp_access_frame_bytes = 77, 
        cpp_name_frame_bytes = 64, ffi_command_bytes = 744, ffi_response_bytes = 1512, 
        ffi_registry_bytes = 96, ffi_handle_tag_bytes = 15, layout_checksum = 423797551137116, 
        max_sites = 32, max_width = 65536), inputs = list(mode = 1, 
        hidden_size = 896, layers = 24, previous_sites = 0, steer_entries = 0, 
        ablate_entries = 0, source_baseline_values = 0, metadata_bytes = 0, 
        metadata_scratch_bytes = 0, existing_direction_estimate = 1404960, 
        r_projection_fixed_bytes = 43720, r_adapter_bytes = 864, 
        max_bytes = 67108864, backend = 0, production_armed = 1), 
    terms = list(direction_bytes = 7184, plan_bytes = 80, context_bytes = 10480, 
        frame_bytes = 14306, probe_bytes = 24209, projection_bytes = 56259, 
        residual_probe_bytes = 0, adapter_data_bytes = 0, adapter_fixed_bytes = 256, 
        metadata_bytes = 0, r_projection_bytes = 58056, r_adapter_bytes = 864, 
        existing_direction_estimate = 1404960, total_bytes = 1520395))
