args <- commandArgs(trailingOnly=TRUE)
stopifnot(length(args)==1L)
path <- normalizePath(args[[1L]],mustWork=TRUE)
stopifnot(!"relm" %in% names(getLoadedDLLs()))
dll <- dyn.load(path,local=TRUE,now=TRUE)
ctor <- getNativeSymbolInfo("wrap__rebirth_projection_construct",PACKAGE=dll)
stopifnot(identical(ctor$numParameters,7L),identical(normalizePath(ctor$dll[["path"]],mustWork=TRUE),path))
z <- .Call(ctor,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
msg <- "Invalid projection admission configuration."
stopifnot(identical(names(z),c("ok","class","message","fields")),identical(z$ok,FALSE),identical(z$class,"relm_error_intervention"),identical(z$message,msg),identical(z$fields,list(reason=msg)))
private <- getNativeSymbolInfo("wrap__rebirth_selftest_projection_combined_logits",PACKAGE=dll)
stopifnot(identical(private$numParameters,1L))
z <- .Call(private,NULL)
msg <- "Projection combined logits selftest is unavailable in this build."
stopifnot(identical(names(z),c("ok","class","message","fields")),identical(z$ok,FALSE),identical(z$class,"relm_error_intervention"),identical(z$message,msg),identical(z$fields,list(reason=msg)))
profile <- .Call(getNativeSymbolInfo("wrap__rebirth_projection_allocation_profile",PACKAGE=dll))
expected_names <- c("version","direction_arc_header_bytes","plan_arc_bytes","site_bytes","runtime_bytes","probe_state_bytes","model_owner_bytes","derive_frame_bytes","callback_frame_bytes","probe_frame_bytes","residual_probe_fixed_bytes","ffi_fixed_bytes","adapter_fixed_bytes","error_format_bytes","metadata_owner_bytes","slot_bytes","proof_bytes","projection_info_bytes","cpp_access_frame_bytes","cpp_name_frame_bytes","ffi_command_bytes","ffi_response_bytes","ffi_registry_bytes","ffi_handle_tag_bytes","layout_checksum","max_sites","max_width")
expected_fixed <- setNames(c(2,16,48,32,5072,56,912,11959,429,153,522,256,150,0,64,152,128,77,64,744,1512,15,423797551137116,32,65536),c("version","direction_arc_header_bytes","plan_arc_bytes","site_bytes","runtime_bytes","probe_state_bytes","model_owner_bytes","derive_frame_bytes","callback_frame_bytes","probe_frame_bytes","residual_probe_fixed_bytes","adapter_fixed_bytes","error_format_bytes","metadata_owner_bytes","slot_bytes","proof_bytes","projection_info_bytes","cpp_access_frame_bytes","cpp_name_frame_bytes","ffi_command_bytes","ffi_response_bytes","ffi_handle_tag_bytes","layout_checksum","max_sites","max_width"))
stopifnot(is.list(profile),identical(names(profile),expected_names))
for(n in names(profile)) stopifnot(typeof(profile[[n]])=="double",length(profile[[n]])==1L,is.finite(profile[[n]]),profile[[n]]>=0,profile[[n]]==floor(profile[[n]]))
for(n in names(expected_fixed)) stopifnot(identical(profile[[n]],as.double(expected_fixed[[n]])))
encoded <- vapply(names(profile),function(n) paste0('"',n,'":',format(profile[[n]],digits=22,scientific=FALSE,trim=TRUE)),character(1))
cat('F6E_PROJECTION_PRODUCTION_PROFILE {"profile":{',paste(encoded,collapse=","),'}}\n',sep="")
cat('F6E_PROJECTION_PRODUCTION_R {"status":"passed","expected_cases":4,"executed_cases":4,"expected_rejections":2,"rejected_cases":2,"model_loads":0,"results":["constructor_registered","constructor_parses_default","fixed_helper_stays_private","compiled_profile_preserved"]}\n')
